import Navbar from "@/components/Navbar"
import Footer from "@/components/Footer"
import styles from "/styles/about.module.css"
import Head from "next/head";
export default function About(){

    return(
        <>
        <Head>
        <title>Findy - Sobre</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <Navbar/>
        <div className={styles.aboutContainer}>
            <h1 className={styles.title}>Sobre</h1>
            <span className={styles.span}></span>
            <p className={styles.titleP}>Conheça mais sobre Findy</p>
        </div>
        <div className={styles.containerAbout}>
            <h3>HISTÓRIA, MISSÃO E VISÃO</h3>
            <p>Quando iniciamos a Bikcraft queriamos apenas um produto que adoraríamos utilizar. Eramos apaixonados por pedalar e também por fazer as coisas com as nossas próprias mãos. Assim surgiu um sonho na garagem da nossa casa.<br/>
Conheça os nossos produtos, pergunte para os nossos clientes e descubra a maravilha de ter uma Bikcraft na sua casa</p>
            <h3>VALORES</h3>
            <p>– Qualidade no processo com
– Foco no cliente sem perder a
– Diversão, preservando a
– Natureza com sustentabilidade</p>
        </div>
        <Footer/>
        </>
        
    )
}