import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer"
import Head from "next/head";
import styles from "styles/Contatos.module.css";
import DivPadrao from "@/components/DivPadrao";

export default function Contato() {
  return (
    <>
      <Head>
        <title>Findy - Contato</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
        ></link>
      </Head>
      <Navbar />
      <DivPadrao/>
      <form
        action="https://formeezy.com/api/v1/forms/FORM_ID/submissions"
        method="POST"
        className={styles.form}
      >
        <input
          type="text"
          name="name"
          placeholder="Enter name"
          required
          className={styles.formInput}
        ></input>
        <input
          type="email"
          name="email"
          placeholder="Enter email"
          required
          className={styles.formInput}
        ></input>
        <textarea
          placeholder="Enter message"
          name="message"
          required
          className={styles.formMessageTxt}
        ></textarea>
        <button type="submit" className={styles.formButton}>Enviar</button>
      </form>
      <div className={styles.conatos_dados}>
          <h3>Dados</h3>
          <span>+55 9999-999</span>
          <span>david-mateus09@hotmail.com</span><br/>
          <span>david-mateus09@hotmail.com</span>
          <span>david-mateus09@hotmail.com</span>
          <h3>Redes sociais</h3>
            <ul className={styles.socials}>
            <li>
              <a href="#">
                <i class="fa fa-facebook"></i>
              </a>
            </li>

            <li>
              <a href="#">
                <i class="fa fa-twitter"></i>
              </a>
            </li>
            <li>
              <a href="#">
                <i class="fa fa-linkedin-square"></i>
              </a>
            </li>

          </ul>
      </div>
      <Footer/>
    </>
  );
}
