import Head from "next/head";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer"
import styles from "../styles/Home.module.css";
import Buttons from "@/components/Buttons";
import Image from "next/image";

export default function Home() {
  return (
    <>
      <Head>
        <title>Findy - Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
        ></link>
      </Head>
      <main>
        <Navbar />
        <div className={styles.container}>
          <h1>
            Findy ajudando voce a enccontra
            <br />
            algo que ama.
          </h1>
          <p>“São Longuinho, São Longuinho, se eu achar...” Vamos lá</p>
          <Buttons />
        </div>

        <div className={styles.containerImg}>
          <Image
            src="/imageHome.png"
            alt="Picture of the author"
            width="400"
            height="400"
          />
        </div>
      </main>

      <Footer/>
    </>
  );
}
